import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBarAboutMe from '../Components/aboutMe/SidebarAboutMe'
import Contacts from '../Components/aboutMe/SidebarSections/Contacts'
import Footer from '../Components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ArticleLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  return (
    <div className='bg-[#011627] flex '>
      {/* <div className='grow '> */}

      <div>
        <SideBarAboutMe>
          <Contacts />
        </SideBarAboutMe>
      </div>

      <div className='grow'>
        {children}

      </div>

      {/* </div> */}
    </div>
  )
}
