import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBarAboutMe from '../Components/aboutMe/SidebarAboutMe'
import FaqSection from '../Components/aboutMe/FaqSection'
import FolderInfo from '../Components/aboutMe/FoldersInfo'
import Contacts from '../Components/aboutMe/SidebarSections/Contacts'
import BioFolder from '../assets/icons/EducationFolder.png'
import InterestsFolder from '../assets/icons/InterestsFolder.png'
import EducationFolder from '../assets/icons/Vector.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AboutMeLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  return (
    <div className='bg-[#011627] flex '>
      <SideBarAboutMe isPageAboutMe> 

        <FaqSection name='personal-info' isOpen>
          <FolderInfo folder={BioFolder} summaryText='bio' detailsDescription='personal-info'/>
          <FolderInfo folder={InterestsFolder} summaryText='interests' detailsDescription='technology'/>
          <FolderInfo folder={EducationFolder} summaryText='education' detailsDescription='university'/>
        </FaqSection>

        <Contacts/>

      </ SideBarAboutMe>
      <div className='grow '>
        {children}
      </div>
    </div>
  )
}
