import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBarAboutMe from '../Components/aboutMe/SidebarAboutMe'
import Header from '../Components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AboutMeLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  return (
    <div className='bg-[#011627] flex'>
      <SideBarAboutMe />
      {children}
    </div>
  )
}
